### ISSUE TITLE
teardown function is not called if test case fails

### ISSUE THREAD

**Issue by nicopernas** [bvdberg/ctest#24]
Hi,

I started seeing test cases failing out of nowhere when they were executed after another test that had just failed. I thought I might be something wrong with my code - maybe I wasn't cleaning up my pointers or memory correctly... after a bit of research I found out that indeed the memory was not being clean up because the teardown function was not being called after a failing test case. 

This simple example shows how the "bye from teardown" message is only being printed once.

``` c
#include <stdio.h>
#include "ctest.h"

CTEST_DATA(foo) {
};

CTEST_SETUP(foo) {
    puts("\nhi from setup");
}

CTEST2(foo, test1) {
    ASSERT_FAIL();
}

CTEST2(foo, test2) {
    ASSERT_TRUE(1);
}

CTEST_TEARDOWN(foo) {
    puts("bye from teardown");
}
```

The output is 

```
$ ./test
TEST 1/2 foo:test2 
hi from setup
bye from teardown
[OK]
TEST 2/2 foo:test1 
hi from setup
[FAIL]
  ERR: mytests.c:13  shouldn't come here
RESULTS: 2 tests (1 ok, 1 failed, 0 skipped) ran in 0 ms
```

If you are OK wit it I could send you a PR to fix it?

Thanks for ctest, I absolutely love it!
Nico

**Comment by bvdberg** [comment]
Hi,

Thx for your feedback! I can look into it this weekend, but if you want to
send a patch, thats also fine..

Thx,
Bas

**Comment by bvdberg** [comment]
Hi,

I'm looking into calling the teardown on failure, but re-discovered I
probably didn't call
the teardown on purpose. It a bit of a design question:

Q: call asserts be used in teardown functions?
Q: should we call teardown() if the setup() fails?

This does introduce some extra complexity and some choices.

I think we shouldn't call teardown if setup fails, otherwise users have to
add extra checking
in teardown, but maybe this is ok.

And if we disallow Asserts in teardown(), ideally the compiler should
ideally prevent this.
